name: MapPlugin
version: '${project.version}'
main: com.czachodym.minecraft.map.mapplugin.MapPlugin
api-version: 1.19

commands:
  markFrame:
    description: Use to mark a frame as a source of an item in it. A cost to do that is one of what you have in your hand.
    usage: /<command>
  cancelMark:
    description: Use to cancel /markFrame before interacting with an entity
    usage: /<command>
  unmarkFrame:
    description: User to unmark already marked frame.
    usage: /<command>
